Repository TusharAMD/Runn, pull requests merged in 2022-05, with the labels that each got.

#90 Tic Tac Toe Ideation added
  games/Tic Tac Toe/README.md
Labels: GSSoC22, Level1

#89 Gesture Control added (Chess Game)
  games/Chess-Game/gesturecontrol.py
Labels: GSSoC22, Level3

#88 Piano Game readme added
  games/Piano Tiles/README.md
Labels: GSSoC22, Level3

#87 Battle city readme added
  games/Battle City Game/README.md
Labels: GSSoC22, Level1

#80 Piano TilesGesture Control added
  games/Piano Tiles/gesturecontrol.py
Labels: GSSoC22, Level3

#99 Tic Tac Toe Game ( Game ) added
  games/Tic Tac Toe/game.py
  games/Tic Tac Toe/logic.py
  games/Tic Tac Toe/main.py
Labels: GSSoC22, Level3

#98 Car Racing (Game) added
  games/Car Racing/main.py
  games/Car Racing/objects.py
Labels: GSSoC22, Level3

#100 breakout game
  games/Breakout-Game/README.md
  games/Breakout-Game/img/Web capture_4-5-2022_222250_127.0.0.1.jpeg
  games/Breakout-Game/index.html
  games/Breakout-Game/script.js
  games/Breakout-Game/style.css
Labels: GSSoC22, Level3

#105 Bounce Game added
  games/Bounce/README.md
  games/Bounce/main.py
  games/Bounce/player.py
Labels: GSSoC22, Level3

#102 Turtle Game
  games/Turtle Game/README.md
  games/Turtle Game/img/add-read.png
  games/Turtle Game/img/ss1turtle.png
  games/Turtle Game/turtle-game.py
Labels: GSSoC22, Level2

#112 Gesture Control added for Bounce
  games/Bounce/gesturecontrol.py
  games/Tetris/gesturecontrol.py
Labels: GSSoC22, Level3

#140 Bounce gesture control readme added
  games/Bounce/README.md
Labels: GSSoC22, Level3

#139 Rock-paper-scissors readme added
  games/Rock-Paper-Scissors-Game/readme.md
Labels: GSSoC22, Level1

#138 Gesture control added
  games/Tic Tac Toe/gesture.py
Labels: GSSoC22, Level3

#137 Memory Puzzle Game added
  games/Memory Puzzle/README.md
  games/Memory Puzzle/game.py
Labels: GSSoC22, Level3

#136 Mine Sweeper Game added
  games/Mine Sweeper/README.md
  games/Mine Sweeper/game.py
Labels: GSSoC22, Level3

#131 Flappy Bird Game added
  games/Flappy Bird/README.md
  games/Flappy Bird/main.py
  games/Flappy Bird/objects.py
Labels: GSSoC22, Level3

#130 AeroBusters Ideation added
  games/AeroBlasters/README.md
Labels: GSSoC22, Level1

#127 Matching Game
  games/Matching Game/README.md
  games/Matching Game/index.html
  games/Matching Game/matchingss1.png
  games/Matching Game/script.js
  games/Matching Game/style.css
Labels: GSSoC22, Level3

#126 Doremon Puzzle Game
  games/Doremon Puzzle Game/1.jpg
  games/Doremon Puzzle Game/10.jpg
  games/Doremon Puzzle Game/2.jpg
  games/Doremon Puzzle Game/3.jpg
  games/Doremon Puzzle Game/4.jpg
  games/Doremon Puzzle Game/5.jpg
  games/Doremon Puzzle Game/6.jpg
  games/Doremon Puzzle Game/7.jpg
  games/Doremon Puzzle Game/8.jpg
  games/Doremon Puzzle Game/9.jpg
  games/Doremon Puzzle Game/README.md
  games/Doremon Puzzle Game/doress.png
  games/Doremon Puzzle Game/index.html
  games/Doremon Puzzle Game/logo.png
  games/Doremon Puzzle Game/puzzle.css
  games/Doremon Puzzle Game/puzzle.js
Labels: GSSoC22, Level3

#143 Rock-paper-scissors game added
  games/Rock-Paper-Scissors-Game/game.py
Labels: GSSoC22, Level3

#145 Analog Clock
  games/Analog Clock/Clock.py
  games/Analog Clock/readme.md
Labels: GSSoC22, Level3

#144 Rock-paper-scissors gesture control added
  games/Rock-Paper-Scissors-Game/gesture.py
Labels: GSSoC22, Level3

#155 Game added AeroBlasters
  games/AeroBlasters/main.py
Labels: GSSoC22, Level3

#154 Gesture control added Flappy Bird
  games/Flappy Bird/gesturecontrol.py
Labels: GSSoC22, Level3

#153 Gesture Control added Memory Puzzle
  games/Memory Puzzle/gesturecontrol.py
Labels: GSSoC22, Level3

#152 Gesture Control added Mine Sweeper
  games/Mine Sweeper/gesturecontrol.py
Labels: GSSoC22, Level3

#147 tetris readme added
  games/Tetris/README.md
Labels: GSSoC22, Level2

#150 Quiz Game
  games/Quiz Game/Quiz.py
  games/Quiz Game/readme.md
Labels: GSSoC22, Level3

#151 Snakes and Ladders Game
  games/Snakes and Ladders Game/S&L.txt
  games/Snakes and Ladders Game/dice.txt
  games/Snakes and Ladders Game/img/Board.png
  games/Snakes and Ladders Game/start.py
Labels: GSSoC22, Level3

#170 Gesture Control added Aero Blasters
  games/AeroBlasters/gesturecontrol.py
Labels: GSSoC22, Level3

#167 Maze Game with solver using python
  games/Maze Game/README.md
  games/Maze Game/main.py
  games/Maze Game/maze.py
  games/Maze Game/maze_solver.py
Labels: GSSoC22, Level2

#124 Space Station Defence Game
  games/Space Station Defence game/main.py
  games/Space Station Defence game/space_station_defense_game_background.gif
Labels: GSSoC22, Level3

#123 Added Dino
  games/Dino Game/background.gif
  games/Dino Game/cactus_small.gif
  games/Dino Game/dino.py
  games/Dino Game/dinosaur.gif
Labels: GSSoC22, Level3

#122 Added Pong
  games/Pong/Pong_bounce.wav
  games/Pong/pong.py
Labels: GSSoC22, Level3

#175 Added Egg Catcher Game
  games/Egg-Catcher/Egg_Catcher_Game.ipynb
  games/Egg-Catcher/README.md
Labels: Level3

#183 Memory puzzle readme added
  games/Memory Puzzle/README.md
Labels: GSSoC22, Level2

#182 Mine sweeper game readme added
  games/Mine Sweeper/README.md
Labels: GSSoC22, Level2

#181 Flappy bird readme added
  games/Flappy Bird/README.md
Labels: GSSoC22, Level2

#177 Connected Game added
  games/Connected/README.md
  games/Connected/main.py
Labels: GSSoC22, Level3

#176 Cave Story Game added
  games/Cave Story/README.md
  games/Cave Story/main.py
Labels: GSSoC22, Level3

#178 Space War
  games/Space War/README.md
  games/Space War/img/add-readme (1).png
  games/Space War/img/spacess.png
  games/Space War/start.py
Labels: GSSoC22, Level3

#208 Added Ludo Game
  games/Ludo Game/Browng.gif
  games/Ludo Game/Ludo Board.gif
  games/Ludo Game/Ludo Board.jpg
  games/Ludo Game/Ludo-game.py
  games/Ludo Game/Ludo.py
  games/Ludo Game/Readme.md
  games/Ludo Game/blue side.gif
  games/Ludo Game/blue.gif
  games/Ludo Game/bluebox.gif
  games/Ludo Game/bluestop.gif
  games/Ludo Game/bod.gif
  games/Ludo Game/center.gif
  games/Ludo Game/green side.gif
  games/Ludo Game/green.gif
  games/Ludo Game/greenbox.gif
  games/Ludo Game/greenstop.gif
  games/Ludo Game/head.gif
  games/Ludo Game/head1.gif
  games/Ludo Game/head2.gif
  games/Ludo Game/head3.gif
  games/Ludo Game/ludo_full_big.jpg
  games/Ludo Game/red side.gif
  games/Ludo Game/red.gif
  games/Ludo Game/redbox.gif
  games/Ludo Game/redstop.gif
  games/Ludo Game/snips/snip1.png
  games/Ludo Game/tail.gif
  games/Ludo Game/tail1.gif
  games/Ludo Game/tail2.gif
  games/Ludo Game/tail3.gif
  games/Ludo Game/test.gif
  games/Ludo Game/whitebox.gif
  games/Ludo Game/yellow side.gif
  games/Ludo Game/yellow.gif
  games/Ludo Game/yellowbox.gif
  games/Ludo Game/yellowstop.gif
Labels: GSSoC22, Level3

#207 Angry Walls readme added
  games/Angry Walls/readme.md
Labels: GSSoC22, Level1

#204 Match the Dot game using python
  games/Dot Game/README.md
  games/Dot Game/start.py
Labels: GSSoC22, Level3

#202 Pool Game
  games/Ball Pool Game/README.md
  games/Ball Pool Game/start.py
Labels: GSSoC22, Level3

#192 Game added Dodgy Walls
  games/Dodgy Walls/README.md
  games/Dodgy Walls/main.py
Labels: GSSoC22, Level3

#191 Gesture Control added Connected
  games/Connected/gesturecontrol.py
Labels: GSSoC22, Level3

#211 Angry Walls game added
  games/Angry Walls/game.py
Labels: GSSoC22, Level3

#232 Password Generator Game
  games/Password Generator Game/password.py
  games/Password Generator Game/readme.md
Labels: Level2

#228 Building Tower
  games/Building Tower/README.md
  games/Building Tower/start.py
Labels: GSSoC22, Level3

#227 Box Clear
  games/Box Clear/README.md
  games/Box Clear/icons/imgonline-com-ua-resize-MgAIfPaYv4DK8.png
  games/Box Clear/icons/mine.png
  games/Box Clear/icons/sad.png
  games/Box Clear/start.py
Labels: GSSoC22, Level3

#220 Game added GhostBusters
  games/GhostBusters/README.md
  games/GhostBusters/main.py
Labels: GSSoC22, Level3

#219 Game added Egg Catching Game
  games/Egg Catching Game/README.md
  games/Egg Catching Game/main.py
Labels: GSSoC22, Level3

#218 Dots and Boxes Game added
  games/Dots&Boxes/README.md
  games/Dots&Boxes/main.py
Labels: GSSoC22, Level3

#216 Drop Ball
  games/Drop Ball/README.md
  games/Drop Ball/start.py
Labels: GSSoC22, Level3

#215 Added Tile Breaker Game
  games/Tile Breaker Game/Readme.md
  games/Tile Breaker Game/snips/snip1.png
  games/Tile Breaker Game/tile-breaker.py
Labels: GSSoC22, Level3

#213 Angry walls gesture added
  games/Angry Walls/gesture.py
Labels: GSSoC22, Level3

#231 Guess The Number
  games/Guess The Number/guess.py
  games/Guess The Number/readme.md
Labels: GSSoC22, Level3

#254 Added Chrome Dino Game using Python
  games/Chrome Dino Game/Readme.md
  games/Chrome Dino Game/main.py
  games/Chrome Dino Game/snips/snip.png
  games/Chrome Dino Game/sprites/cacti-big.png
  games/Chrome Dino Game/sprites/cacti-small.png
  games/Chrome Dino Game/sprites/checkPoint.wav
  games/Chrome Dino Game/sprites/cloud.png
  games/Chrome Dino Game/sprites/die.wav
  games/Chrome Dino Game/sprites/dino.png
  games/Chrome Dino Game/sprites/dino_ducking.png
  games/Chrome Dino Game/sprites/game_over.png
  games/Chrome Dino Game/sprites/ground.png
  games/Chrome Dino Game/sprites/jump.wav
  games/Chrome Dino Game/sprites/logo.png
  games/Chrome Dino Game/sprites/numbers.png
  games/Chrome Dino Game/sprites/offline-sprite-2x-black.png
  games/Chrome Dino Game/sprites/ptera.png
  games/Chrome Dino Game/sprites/replay_button.png
Labels: GSSoC22, Level3

#253 Game Complete Jungle Dash
  games/Jungle Dash/README.md
  games/Jungle Dash/main.py
  games/Jungle Dash/objects.py
Labels: GSSoC22, Level3

#252 Game complete Hyper Tile Dash
  games/Hyper Tile Dash/README.md
  games/Hyper Tile Dash/main.py
  games/Hyper Tile Dash/objects.py
Labels: GSSoC22, Level3

#251 Game added Hex Dash
  games/Hex Dash/README.md
  games/Hex Dash/main.py
  games/Hex Dash/objects.py
Labels: GSSoC22, Level3

#250 Random Name Generator
  games/Random Name Generator/randomname.py
  games/Random Name Generator/readme.md
Labels: GSSoC22, Level2

#236 Gesture Control added Ghost Busters
  games/GhostBusters/gesturecontrol.py
Labels: GSSoC22, Level3

#235 Gesture Control added Egg Catching Game
  games/Egg Catching Game/gesturecontrol.py
Labels: Level3

#234 Gesture Control added Dots&Boxes
  games/Dots&Boxes/gesturecontrol.py
Labels: GSSoC22, Level3

#214 Love calculator 💘
  games/Love Calculator/love.py
  games/Love Calculator/readme.md
Labels: GSSoC22, Level3

#262 Dodge Ball
  games/Dodge Ball/README.md
  games/Dodge Ball/start.py
Labels: GSSoC22, Level3

#264 Fighting Game
  games/Fighting Game/README.md
  games/Fighting Game/settings.txt
  games/Fighting Game/start.py
Labels: GSSoC22, Level3

#289 Added Typing Game
  games/Typing Game/Readme.md
  games/Typing Game/logo.ico
  games/Typing Game/snips/snip.png
  games/Typing Game/typing-game.py
  games/Typing Game/words.py
Labels: GSSoC22, Level3

#278 Word Guessing game
  games/Word Guessing game/readme.md
  games/Word Guessing game/wordGuess.py
Labels: GSSoC22, Level3

#270 Tile-o-Tiles, #261
  games/Memory Game/memory.py
  games/Memory Game/readme.md
  games/Tile-O-Tiles/readme.md
  games/Tile-O-Tiles/tile.py
Labels: GSSoC22, Level3

#298 Delete Browser History
  games/delete.py
  games/readme.md
Labels: GSSoC22, Level3

#302 FIdget Spinner Animation in python
  games/Fidget Spinner/fidget.py
  games/Fidget Spinner/readme.md
Labels: GSSoC22, Level3

#344 Ghost busters readme added
  games/GhostBusters/README.md
Labels: GSSoC22, Level1

#343 Egg catching game readme added
  games/Egg Catching Game/README.md
Labels: GSSoC22, Level1

#342 Cave story readme added
  games/Cave Story/README.md
Labels: GSSoC22, Level1

#341 Dodgy walls readme added
  games/Dodgy Walls/README.md
Labels: GSSoC22, Level1

#340 Rock,paper,scissor
  games/Rock ,Paper,scissor/game/description.md
  games/Rock ,Paper,scissor/game/rock,paper,scisoor_game.py
Labels: GSSoC22, Level3

#339 Added Snakes and Ladders Game using Python
  games/Snakes and Ladders/Readme.md
  games/Snakes and Ladders/board.gif
  games/Snakes and Ladders/diceMove.py
  games/Snakes and Ladders/main.py
  games/Snakes and Ladders/snips/snip.png
  games/Snakes and Ladders/userInterface.py
Labels: GSSoC22, Level3

#336 Quiz Math
  games/Quiz Math/README.md
  games/Quiz Math/start.py
Labels: GSSoC22, Level3

#335 Guess Color game
  games/Guess Color/README.md
  games/Guess Color/img/game-console.ico
  games/Guess Color/start.py
Labels: GSSoC22, Level3

#330 Sudoku Solver using Python
  games/Sudoku Solver/readme.md
  games/Sudoku Solver/sudoku.py
Labels: GSSoC22, Level3

#325 Added Checkers Game using Python
  games/Checkers Game/Readme.md
  games/Checkers Game/checkers.py
  games/Checkers Game/snips/snip1.png
Labels: GSSoC22, Level3

#322 Sudoku Solver
  games/Sudoku Solver/README.md
  games/Sudoku Solver/css/style.css
  games/Sudoku Solver/index.html
  games/Sudoku Solver/js/script.js
Labels: GSSoC22, Level3

#321 Destroyer Tank
  games/Destroyer-Tank/README.md
  games/Destroyer-Tank/start.py
Labels: GSSoC22, Level3

#320 Added Tetris Game using Python
  games/Tetris Game/Readme.md
  games/Tetris Game/snips/snip.png
  games/Tetris Game/tetris.py
Labels: GSSoC22, Level3

#318 Game added Pong
  games/Pong1/README.md
  games/Pong1/game.py
Labels: GSSoC22, Level3

#308 Added PacMan Game using Python
  games/PacMan Game/PressStart2P-Regular.ttf
  games/PacMan Game/Readme.md
  games/PacMan Game/animation.py
  games/PacMan Game/constants.py
  games/PacMan Game/constants.py~
  games/PacMan Game/entity.py
  games/PacMan Game/fruit.py
  games/PacMan Game/ghosts.py
  games/PacMan Game/junk.py
  games/PacMan Game/maze1.txt
  games/PacMan Game/maze1_rotation.txt
  games/PacMan Game/maze2.txt
  games/PacMan Game/maze2_rotation.txt
  games/PacMan Game/mazedata.py
  games/PacMan Game/mazes.py~
  games/PacMan Game/mazetest.txt
  games/PacMan Game/modes.py
  games/PacMan Game/nodes.py
  games/PacMan Game/pacman.py
  games/PacMan Game/pauser.py
  games/PacMan Game/pellets.py
  games/PacMan Game/run.py
  games/PacMan Game/run.py~
  games/PacMan Game/snips/snip.png
  games/PacMan Game/sprites.py
  games/PacMan Game/spritesheet.png
  games/PacMan Game/spritesheet_mspacman.png
  games/PacMan Game/spritesheet_pacman2.png
  games/PacMan Game/text.py
  games/PacMan Game/vector.py
Labels: GSSoC22, Level3

#319 Level Designer Game added
  games/Level Designer/README.md
  games/Level Designer/game.py
  games/Level Designer/images/backgroundColorGrass.png
  games/Level Designer/images/delete.py
Labels: GSSoC22, Level3

#345 Rubik Cube Solver
  games/RubikSolver/Rubik.py
  games/RubikSolver/readme.md
Labels: GSSoC22, Level3

#377 Racing game added
  games/Race Car Game/README.MD
  games/Race Car Game/bg.jpg
  games/Race Car Game/car.png
  games/Race Car Game/index.html
  games/Race Car Game/main.js
  games/Race Car Game/style.css
  games/Race Car Game/trfcar.png
  games/Sudoku Solver/README.md
  games/Sudoku Solver/readme.md
Labels: GSSoC22, Level3

#369 Hangman Game
  games/Hangman Game/hangman.py
  games/Hangman Game/readme.md
Labels: GSSoC22, Level3

#368 Create readme.md
  games/Asteroids/readme.md
Labels: GSSoC22, Level3

#358 road-crossing-game
  games/Road-crossing-game-python/README.md
  games/Road-crossing-game-python/car_manager.py
  games/Road-crossing-game-python/main.py
  games/Road-crossing-game-python/player.py
  games/Road-crossing-game-python/scoreboard.py
Labels: GSSoC22, Level3

#356 Ideation added Missile Command
  games/Missile Command/README.md
Labels: GSSoC22, Level1

#355 Ideation added Arkanoid
  games/Arkanoid/README.md
Labels: GSSoC22, Level1

#354 Ideation added Hydro Thunder
  games/Hyrdo Thunder/README.md
Labels: GSSoC22

#348 Paman Game
  games/Paman Game/game.py
  games/Paman Game/readme.md
Labels: GSSoC22, Level3

#385 Added 2D Chess Game using Python
  games/Chess Game/Readme.md
  games/Chess Game/chessboard.py
  games/Chess Game/main.py
  games/Chess Game/pieces.py
  games/Chess Game/pieces_image/bblack.png
  games/Chess Game/pieces_image/bwhite.png
  games/Chess Game/pieces_image/kblack.png
  games/Chess Game/pieces_image/kwhite.png
  games/Chess Game/pieces_image/nblack.png
  games/Chess Game/pieces_image/nwhite.png
  games/Chess Game/pieces_image/pblack.png
  games/Chess Game/pieces_image/pwhite.png
  games/Chess Game/pieces_image/qblack.png
  games/Chess Game/pieces_image/qwhite.png
  games/Chess Game/pieces_image/rblack.png
  games/Chess Game/pieces_image/rwhite.png
  games/Chess Game/snips/snip.png
  games/Chess Game/test.py
Labels: GSSoC22, Level3

#384 Added Fruit Ninja Game using Python
  games/Fruit Ninja Game/Readme.md
  games/Fruit Ninja Game/back.jpg
  games/Fruit Ninja Game/comic.ttf
  games/Fruit Ninja Game/images/backgound.jpg
  games/Fruit Ninja Game/images/bomb.png
  games/Fruit Ninja Game/images/explosion.png
  games/Fruit Ninja Game/images/game_over.png
  games/Fruit Ninja Game/images/guava.png
  games/Fruit Ninja Game/images/half_guava.png
  games/Fruit Ninja Game/images/half_melon.png
  games/Fruit Ninja Game/images/half_orange.png
  games/Fruit Ninja Game/images/half_pomegranate.png
  games/Fruit Ninja Game/images/melon.png
  games/Fruit Ninja Game/images/orange.png
  games/Fruit Ninja Game/images/pomegranate.png
  games/Fruit Ninja Game/images/red_lives.png
  games/Fruit Ninja Game/images/white_lives.png
  games/Fruit Ninja Game/main.py
  games/Fruit Ninja Game/snips/snip.png
Labels: GSSoC22, Level3

#383 Added Balloon Popper Game using Python
  games/Balloon Popper Game/Balloon.py
  games/Balloon Popper Game/Button.py
  games/Balloon Popper Game/Engine.py
  games/Balloon Popper Game/Instructions.py
  games/Balloon Popper Game/Kitten.py
  games/Balloon Popper Game/Readme.md
  games/Balloon Popper Game/Scoreboard.py
  games/Balloon Popper Game/Settings.py
  games/Balloon Popper Game/Sword.py
  games/Balloon Popper Game/green_balloon_50px.png
  games/Balloon Popper Game/kitten_50px.png
  games/Balloon Popper Game/main.py
  games/Balloon Popper Game/snips/snips.png
  games/Balloon Popper Game/sword_75px.png
Labels: GSSoC22, Level3

#371 Snake Arcade Game in python
  games/Sanke Arcade Game/game.py
  games/Sanke Arcade Game/readme.md
Labels: GSSoC22, Level3

#386 Added Drawing App using Python
  games/Paint App/Readme.md
  games/Paint App/main.py
  games/Paint App/snips/snip1.png
Labels: GSSoC22, Level3

#388 Tron game
  games/Tron Game/game.py
Labels: GSSoC22, Level2

#390 Real time cannon game
  games/Cannon Game/code.py
  games/Cannon Game/readme.md
Labels: GSSoC22, Level3

#389 Hey Life-Stimulation Game
  games/Hey Life-Stimulation Game/game.py
  games/Hey Life-Stimulation Game/readme.md
Labels: GSSoC22, Level3

#430 Traffic running
  games/Traffic running/README.md
  games/Traffic running/img/bg.jpg
  games/Traffic running/img/car.png
  games/Traffic running/img/opponent car.png
  games/Traffic running/index.html
  games/Traffic running/script.js
  games/Traffic running/style.css
Labels: GSSoC22, Level3

#429 Rubic Cube
  games/Rubic Cube/README.md
  games/Rubic Cube/index.html
  games/Rubic Cube/script.js
  games/Rubic Cube/style.css
Labels: GSSoC22, Level3

#428 Added Doodle Jump Game
  games/Doodle Jump/Clouds.py
  games/Doodle Jump/Clouds.pyc
  games/Doodle Jump/Readme.md
  games/Doodle Jump/background.jpg
  games/Doodle Jump/background.png
  games/Doodle Jump/blue_back.jpg
  games/Doodle Jump/character.bmp
  games/Doodle Jump/clouds_img/cloud1.png
  games/Doodle Jump/clouds_img/cloud2.png
  games/Doodle Jump/clouds_img/cloud3.png
  games/Doodle Jump/clouds_img/clouds.zip
  games/Doodle Jump/doodlejump.py
  games/Doodle Jump/enemies.py
  games/Doodle Jump/enemies.pyc
  games/Doodle Jump/highscore.txt
  games/Doodle Jump/layer-1.png
  games/Doodle Jump/layer-2.png
  games/Doodle Jump/lowPlatform.py
  games/Doodle Jump/lowPlatform.pyc
  games/Doodle Jump/main.py
  games/Doodle Jump/main.pyc
  games/Doodle Jump/meowth1.png
  games/Doodle Jump/meowth2.png
  games/Doodle Jump/pikachu.png
  games/Doodle Jump/platforms.py
  games/Doodle Jump/platforms.pyc
  games/Doodle Jump/player.py
  games/Doodle Jump/player.pyc
  games/Doodle Jump/powerup.py
  games/Doodle Jump/powerup.pyc
  games/Doodle Jump/settings.py
  games/Doodle Jump/settings.pyc
  games/Doodle Jump/snips/snip1.png
  games/Doodle Jump/sound/background_music.ogg
  games/Doodle Jump/sound/jump.ogg
  games/Doodle Jump/sound/pow.wav
  games/Doodle Jump/spritesheet_jumper.png
  games/Doodle Jump/spritesheet_jumper.xml
  games/Doodle Jump/spritesheets.py
  games/Doodle Jump/spritesheets.pyc
  games/Doodle Jump/tile.png
Labels: GSSoC22, Level3

#427 Rock Paper Scissor
  games/Rock Paper Scissor/game.py
  games/Rock Paper Scissor/readme.md
Labels: GSSoC22, Level3

#423 Carrom board
  games/Carrom/README.md
  games/Carrom/start.py
Labels: GSSoC22, Level3

#417 Caterpiller Game
  games/Catterpiller Game/catter.py
  games/Catterpiller Game/readme.md
Labels: GSSoC22, Level3

#403 Game of Words
  games/Word Game/code.py
Labels: GSSoC22, Level3

#398 Bagels Game
  Bagels Game/code.py
Labels: GSSoC22, Level3

#397 Added Shuffle Word Guess Game
  games/Shuffle Word Guess Game/Options/Animals.py
  games/Shuffle Word Guess Game/Options/Body_parts.py
  games/Shuffle Word Guess Game/Options/Colour.py
  games/Shuffle Word Guess Game/Options/Fruit.py
  games/Shuffle Word Guess Game/Options/Shapes.py
  games/Shuffle Word Guess Game/Options/Vegetable.py
  games/Shuffle Word Guess Game/Options/Vehicles.py
  games/Shuffle Word Guess Game/Readme.md
  games/Shuffle Word Guess Game/back.png
  games/Shuffle Word Guess Game/index.py
  games/Shuffle Word Guess Game/snips/snip1.png
Labels: GSSoC22, Level3

#395 Python Card Game
  games/CardGame/card.py
  games/CardGame/readme.md
Labels: GSSoC22, Level3

#394 PET SCREEN GAME
  games/Pet Screen Game/pet.md
  games/Pet Screen Game/pet.py
Labels: GSSoC22, Level3

#441 Aestroid Game
  games/Aestroid Game/code.py
Labels: GSSoC22, Level3

#443 Added quiz game
  Math Quiz/quiz.py
Labels: GSSoC22, Level3

#442 Move those Walls
  games/Move Walls Game/code.py
Labels: GSSoC22, Level3

#446 Added Tic Tac Toe Game using Python
  games/Tic Tac Toe Game/O.png
  games/Tic Tac Toe Game/Readme.md
  games/Tic Tac Toe Game/X.png
  games/Tic Tac Toe Game/snips/snip1.png
  games/Tic Tac Toe Game/tic tac opening.png
  games/Tic Tac Toe Game/tictactoe.py
Labels: GSSoC22, Level3

#445 Added 2048 Game using Python
  games/2048 Game/Readme.md
  games/2048 Game/func.py
  games/2048 Game/main.py
  games/2048 Game/snips/snip1.png
Labels: GSSoC22, Level3

#444 Portal game
  games/Portal Game/index.html
Labels: GSSoC22, Level3

#475 added paint Game
  games/Paint Game/paint.py
  games/Paint Game/readme.md
Labels: GSSoC22, Level3

#472 Snake game added
  games/Snake Game/assets/effects/music_eating.mp3
  games/Snake Game/assets/effects/music_gameover.mp3
  games/Snake Game/assets/effects/music_move.mp3
  games/Snake Game/assets/img/background.jpg
  games/Snake Game/index.html
  games/Snake Game/snake.css
  games/Snake Game/snake.js
Labels: GSSoC22, Level3

#465 Spaceship Game
  games/Spaceship Game/game.py
Labels: GSSoC22, Level3

#464 Jungle Game
  games/Jungle Game/game.py
Labels: GSSoC22, Level3

#463 Car Racing Game
  games/Car Racing Game/game.py
Labels: GSSoC22, Level3

#462 Ghostbusters Game
  games/Ghostbusters Game/game.py
Labels: GSSoC22, Level3

#461 Added Memory Card Game using Python
  games/Memory Card Game/OpenSans-Light.ttf
  games/Memory Card Game/OpenSans-Regular.ttf
  games/Memory Card Game/Readme.md
  games/Memory Card Game/card.py
  games/Memory Card Game/memory.py
  games/Memory Card Game/snips/snip1.png
Labels: GSSoC22, Level3

#455 Dodge Game
  games/Dodge Game/dodge.py
  games/Dodge Game/readme.md
Labels: GSSoC22, Level3

#451 Sparkle Pointer code added
  games/Sparkle Pointer/README.md
  games/Sparkle Pointer/main.py
Labels: GSSoC22, Level3

#450 Ideation added Tron Game
  games/Tron/README.md
Labels: GSSoC22, Level3

#449 Ideation added Out Run
  games/OutRun/README.md
Labels: GSSoC22, Level3

#448 Ideation added Xexex
  games/Virtua Racing/README.md
  games/Xexex/README.md
Labels: GSSoC22, Level3

#503 Added Simon Says Game using Python
  games/Simon Says Game/Readme.md
  games/Simon Says Game/main.py
  games/Simon Says Game/snips/snip1.png
Labels: GSSoC22, Level3

#491 Hangman Game
  games/Hangman-Game/IMG/hangman0.png
  games/Hangman-Game/IMG/hangman1.png
  games/Hangman-Game/IMG/hangman2.png
  games/Hangman-Game/IMG/hangman3.png
  games/Hangman-Game/IMG/hangman4.png
  games/Hangman-Game/IMG/hangman5.png
  games/Hangman-Game/IMG/hangman6.png
  games/Hangman-Game/README.md
  games/Hangman-Game/game.py
Labels: GSSoC22, Level3

#490 Added Golf game
  games/Golf Game/IMG/back.png
  games/Golf Game/IMG/coin1.png
  games/Golf Game/IMG/coin2.png
  games/Golf Game/IMG/coin3.png
  games/Golf Game/IMG/course1.png
  games/Golf Game/IMG/flag.png
  games/Golf Game/IMG/green.png
  games/Golf Game/IMG/laser.png
  games/Golf Game/IMG/power.png
  games/Golf Game/IMG/sand.png
  games/Golf Game/IMG/sandBottom.png
  games/Golf Game/IMG/sandEdge.png
  games/Golf Game/IMG/sticky.png
  games/Golf Game/IMG/water.png
  games/Golf Game/game.py
  games/Golf Game/laws.py
  games/Golf Game/level.py
  games/Golf Game/main.py
Labels: GSSoC22, Level3

#487 Level Designer readme added
  games/Level Designer/README.md
Labels: GSSoC22, Level2

#486 Dots&Boxes ideation added
  games/Dots&Boxes/README.md
Labels: GSSoC22, Level2

#485 Asteroids gesture added
  games/Asteroids/gesture.py
Labels: GSSoC22, Level3

#484 Asteroids game created
  games/Asteroids/game.py
Labels: GSSoC22, Level3

#483 Added Space Invaders Game using Python
  games/Space Invaders Game/Readme.md
  games/Space Invaders Game/assets/background-black.png
  games/Space Invaders Game/assets/pixel_laser_blue.png
  games/Space Invaders Game/assets/pixel_laser_green.png
  games/Space Invaders Game/assets/pixel_laser_red.png
  games/Space Invaders Game/assets/pixel_laser_yellow.png
  games/Space Invaders Game/assets/pixel_ship_blue_small.png
  games/Space Invaders Game/assets/pixel_ship_green_small.png
  games/Space Invaders Game/assets/pixel_ship_red_small.png
  games/Space Invaders Game/assets/pixel_ship_yellow.png
  games/Space Invaders Game/main.py
  games/Space Invaders Game/snips/snip1.png
Labels: GSSoC22, Level3

#482 Catch fruit game using python
  games/Fruit Catch/README.md
  games/Fruit Catch/high-score.txt
  games/Fruit Catch/images/ananas.gif
  games/Fruit Catch/images/apple.gif
  games/Fruit Catch/images/candy1.gif
  games/Fruit Catch/images/candy2.gif
  games/Fruit Catch/images/jew.gif
  games/Fruit Catch/images/lollypop.gif
  games/Fruit Catch/images/orange.gif
  games/Fruit Catch/start.py
Labels: GSSoC22, Level3

#529 Added Ludo Game Files
  LudoGame/1.png
  LudoGame/2.png
  LudoGame/3.png
  LudoGame/4.png
  LudoGame/README.md
  LudoGame/ludo/__init__.py
  LudoGame/ludo/cli.py
  LudoGame/ludo/game.py
  LudoGame/ludo/painter.py
  LudoGame/ludo/recorder.py
  LudoGame/run.py
Labels: GSSoC22, Level3
