Repository TusharAMD/Runn, pull requests merged in 2022-04, with the labels that each got.

#38 Subway-Sufer Added
  SubwaySufer Game Using Pose Detection and mediapipe/SubWay Sufers  Game using Media Pipe and Posture Detection.ipynb
Labels: GSSoC22, Level3

#42 Issue #32 Car Racing Gesture Added
  games/Car Racing/README.md
  games/Car Racing/color.py
  games/Car Racing/controlling_steer.py
  games/Car Racing/directkeys.py
  games/Car Racing/requirements.py
Labels: GSSoC22, Level3

#50 Snake GameGesture Control added
  games/Snake-Game/game-control-using-object-tracking.py
  games/Snake-Game/object-detection.py
  games/Snake-Game/requirements.txt
Labels: GSSoC22, Level3

#49 Added a code for color and Shape detection
  games/color detection of an object/colorandshape.py
  games/color detection of an object/test_image_2.png
Labels: GSSoC22, Level1

#58 Snake game Ideation added
  games/Snake-Game/README.md
Labels: GSSoC22, Level1

#57 Mario game (Game) complete
  games/Mario-Game/MarioGame.py
  games/Mario-Game/README.md
  games/Mario-Game/requirements.txt
Labels: GSSoC22, Level3

#60 Gesture Control for Dino-Game added
  games/Dino-Game/README.md
  games/Dino-Game/config.py
  games/Dino-Game/gesturecontrol.py
Labels: Level3

#59 Gesture Control For Mario Added
  games/Mario-Game/config.py
  games/Mario-Game/gesturecontrol.py
Labels: GSSoC22, Level3

#64 Sudoku readme added
  games/Sudoku-game/Readme.md
Labels: GSSoC22, Level1

#65 Mario Gesture Control game readme added
  games/Mario-Game/README.md
Labels: GSSoC22, Level1

#68 Battle City Game (Game) added
  games/Battle City Game/README.md
  games/Battle City Game/images/01.png
  games/Battle City Game/images/02.png
  games/Battle City Game/images/06.png
  games/Battle City Game/images/delete.py
  games/Battle City Game/images/sprites.gif
  games/Battle City Game/levels/1
  games/Battle City Game/levels/10
  games/Battle City Game/levels/11
  games/Battle City Game/levels/12
  games/Battle City Game/levels/13
  games/Battle City Game/levels/14
  games/Battle City Game/levels/15
  games/Battle City Game/levels/16
  games/Battle City Game/levels/17
  games/Battle City Game/levels/18
  games/Battle City Game/levels/19
  games/Battle City Game/levels/2
  games/Battle City Game/levels/20
  games/Battle City Game/levels/21
  games/Battle City Game/levels/22
  games/Battle City Game/levels/23
  games/Battle City Game/levels/24
  games/Battle City Game/levels/25
  games/Battle City Game/levels/26
  games/Battle City Game/levels/27
  games/Battle City Game/levels/28
  games/Battle City Game/levels/29
  games/Battle City Game/levels/3
  games/Battle City Game/levels/30
  games/Battle City Game/levels/31
  games/Battle City Game/levels/32
  games/Battle City Game/levels/33
  games/Battle City Game/levels/34
  games/Battle City Game/levels/35
  games/Battle City Game/levels/4
  games/Battle City Game/levels/5
  games/Battle City Game/levels/6
  games/Battle City Game/levels/7
  games/Battle City Game/levels/8
  games/Battle City Game/levels/9
  games/Battle City Game/levels/delete.py
  games/Battle City Game/tanks.py
Labels: GSSoC22, Level3

#66 Sudoku Gesture Control added
  games/Sudoku-game/Automatic-Sudoku-Solver.ipynb
  games/Sudoku-game/assets/Input puzzle.png
  games/Sudoku-game/assets/binary graded puzzle.png
  games/Sudoku-game/assets/cropped puzzle.png
  games/Sudoku-game/assets/delete.py
  games/Sudoku-game/assets/digit extraction.png
  games/Sudoku-game/assets/grayscale puzzle.png
  games/Sudoku-game/assets/grid lines puzzle.png
  games/Sudoku-game/assets/intersection puzzle.png
  games/Sudoku-game/assets/pre-processed image.png
  games/Sudoku-game/assets/sudoku outline.png
Labels: GSSoC22, Level3

#75 Dinosaur game readme added
  games/Dino-Game/README.md
Labels: GSSoC22, Level2

#76 Dinosaur game added
  games/Dino-Game/game.py
Labels: GSSoC22, Level3

#78 Sudoku-Game added
  games/Sudoku-game/sudoku-game.py
Labels: GSSoC22, Level3

#79 Piano Tiles (Game) added
  games/Piano Tiles/README.md
  games/Piano Tiles/main.py
  games/Piano Tiles/notes.py
Labels: GSSoC22, Level3
