Repository TusharAMD/Runn, pull requests merged in 2024-01, with the labels that each got.

#565 Update Readme.md
  games/Hit_me_toy/Readme.md
Labels: IWOC2024, Easy

#569 ladoo catcher game
  games/Ladoo_Catcher/asteroid.png
  games/Ladoo_Catcher/ladoo.png
  games/Ladoo_Catcher/ladoo_catcher.py
  games/Ladoo_Catcher/net.png
Labels: IWOC2024, Medium

#579 Adde Game
  games/Aplhabetize-quiz/README.md
  games/Aplhabetize-quiz/main.py
Labels: IWOC2024, Hard

#575 added games
  games/Campfire/Readme.md
  games/Campfire/campfire_game.py
  games/Paper_Plane/Paper_plane_gesture.py
  games/Paper_Plane/Readme.md
Labels: IWOC2024, Medium

#585 add 3d snake game
  games/3D Snake Game/index.html
  games/3D Snake Game/readme.md
  games/3D Snake Game/script.js
  games/3D Snake Game/style.css
Labels: IWOC2024, Hard

#584 Added ladoo catcher game
  games/Ladoo_Catcher/CoreGame.py
Labels: IWOC2024, Hard

#583 Hit me toy game added
  games/Hit_me_toy/Hit-Me-Toy.py
Labels: IWOC2024, Hard

#596 add cable_maze game
  games/Cable_maze/index.html
  games/Cable_maze/main.js
  games/Cable_maze/readme.md
Labels: IWOC2024, Medium

#595 add breakout_game
  games/Breakout_game/index.html
  games/Breakout_game/readme.md
  games/Breakout_game/script.js
  games/Breakout_game/style.css
Labels: IWOC2024, Medium

#589 Added Rotating Cube + Documentation
  games/Rotating-Game/README.md
  games/Rotating-Game/main.py
Labels: IWOC2024, Medium

#587 Added Chance Checkers + Documnetation
  games/Chance-Checkers/README.md
  games/Chance-Checkers/main.py
Labels: IWOC2024, Medium

#586 Added Barca Game + Documentation
  games/Barca/README.md
  games/Barca/main.py
Labels: IWOC2024, Medium

#602 add doodle_jump game
  games/Doodle_game/Readme.md
  games/Doodle_game/index.html
  games/Doodle_game/script.js
  games/Doodle_game/stylr.css
Labels: IWOC2024, Medium

#599 Added Ghost Leg Lottery Game
  games/Ghost-Leg-Lottery/README.md
  games/Ghost-Leg-Lottery/main.py
Labels: IWOC2024, Medium

#603 add brick_break game
  games/Brick_break_game/Readme.md
  games/Brick_break_game/index.html
  games/Brick_break_game/script.js
  games/Brick_break_game/style.css
Labels: IWOC2024, Medium

#600 Added Monalisa
  games/Monalisa/README.md
  games/Monalisa/main.py
Labels: IWOC2024, Medium

#601 Added Random Walk Game
  games/Random-Walk/README.md
  games/Random-Walk/main.py
Labels: IWOC2024, Medium

#605 add Blackzone game
  games/Black_zone_game/index.html
  games/Black_zone_game/readme.md
  games/Black_zone_game/script.js
  games/Black_zone_game/style.css
Labels: IWOC2024, Medium

#608 Added game
  games/Sliding-Tile-Puzzle-Game/README.md
  games/Sliding-Tile-Puzzle-Game/main.py
Labels: IWOC2024, Medium

#612 add Dragon_world_game
  games/Dragon-world-game/assets/cover.png
  games/Dragon-world-game/assets/dragon.png
  games/Dragon-world-game/assets/dragon_world.png
  games/Dragon-world-game/assets/obstacle.png
  games/Dragon-world-game/index.html
  games/Dragon-world-game/readme.md
  games/Dragon-world-game/script.js
  games/Dragon-world-game/style.css
Labels: IWOC2024, Medium

#616 add CampFire_game
  games/Campfire_game/index.html
  games/Campfire_game/readme.md
  games/Campfire_game/script.js
  games/Campfire_game/style.css
Labels: IWOC2024, Medium

#617 Added Sand simulator game
  games/Sand-Simulator/README.md
  games/Sand-Simulator/main.py
Labels: IWOC2024, Medium

#618 Added Maze runner 2d game
  games/Maze-Runner-2d/README.md
  games/Maze-Runner-2d/main.py
Labels: IWOC2024, Medium

#619 Added Nonuniform Fractal Tree Drawer Game
  games/Non-uniform-Fractal-Tree-Drawer/README.md
  games/Non-uniform-Fractal-Tree-Drawer/main.py
Labels: IWOC2024, Medium

#627 Added Zombie bite fight game
  games/Zombie-Bite-Fight/README.md
  games/Zombie-Bite-Fight/main.py
Labels: IWOC2024, Medium

#629 Added water bucket game
  games/Water-Bucket-Game/README.md
  games/Water-Bucket-Game/main.py
Labels: IWOC2024, Medium
